appName: app-flask-hello
deploymentName: dep-flask-hello
servName: svc-flask-hello
contatinerName: cont-flask-hello

replicas: 4

port: 5000

image:
  name: geektechstuff/flask-hello-world
  tag: latest

